version: '3.9'
services:
  next-app:
    image: tne-next-dev-i
    build: 
      dockerfile: Dockerfile.dev
    container_name: tne-next-dev-c
    volumes: 
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3001"
  firebase-emulator:
    build:
      dockerfile: Dockerfile.firebase
      args:
        - FIREBASE_VERSION=13.5.1
    stop_grace_period: 1m
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099"
      FIRESTORE_EMULATOR_HOST: "localhost:8080"
      PUBSUB_EMULATOR_HOST: "localhost:8085"
      FUNCTIONS_EMULATOR_HOST: "localhost:5001"
      FIREBASE_PROJECT: "test-project"
      FORCE_COLOR: 'true'
      DATA_DIRECTORY: "data"
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "4000:4001" # ui
      - "4400:4401" # hub
      - "4600:4601" # logging
      # - "5001:5002" # functions
      # - "8080:8081" # firestore
      - "8085:8086" # pubsub
      # - "9000:9001" # database
      - "9099:9100" # auth
      # - "9199:9200" # Storage
      # - "6000:6001" # Hosting
    volumes:
      - ./firebase:/srv/firebase:rw
      - ./cache:/root/.cache/:rw
      - ~/.config/:/root/.config
      - ./firebase/data:/srv/firebase/data:rw
volumes:
  node_modules:
  # db:
  #   image: postgres:16.2-alpine
  #   container_name: throw-new-error-db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - '${POSTGRES_PORT}:5432'
  #   volumes:
  #     - /var/lib/postgresql/data
  #     - ./docker/config/postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     PGDATA: ${PGDATA}
