import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/components/store-provider'
import { headers } from 'next/headers'
import Header from '@/features/layout/components/header'
import getUserDataFromSession from '@/features/auth/helpers/get-user-data-from-session'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = headers()
  const csrfToken = headersList.get('csrfToken')
  if (csrfToken === null) {
    throw new Error('CSRF Token not set')
  }
  const user = await getUserDataFromSession()

  return (
    <StoreProvider csrfToken={csrfToken} user={user}>
      <html lang="en">
        <body className={inter.variable}>
          <Header />
          {children}
        </body>
      </html>
    </StoreProvider>
  )
}
